version: "3.8"
services:
  frontend:
    container_name: frontend-monorepo
    build:
      context: ./frontend
    working_dir: /app
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend
    environment:
      - VITE_DEV_SERVER=true
    networks:
      - app_network

  backend:
    container_name: backend-monorepo
    build:
      context: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"
    command: sh -c "npm install && npx ts-node-dev src/index.ts"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/myapp_dev
    depends_on:
      - db

  db:
    container_name: db-monorepo
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    container_name: adminer-monorepo
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata:

networks:
  app_network:
